site:
  baseline: My blog note
  baseurl: /
  canonicalurl: true
  date:
    format: j F Y
    timezone: Bangladesh/Dhaka
  description: Starter blog
  netlify:
    cms:
      path: admin
      version: latest
    identity:
      version: v1
  pagination:
    max: 10
    path: page
  title: NotesOfLiit
theme: hyde
